column = ['Pieces',
'Chargewt',
'agent_ARAB BBS',
'agent_MAINABBS',
'agent_JJFRBBS',
'agent_H G RBBS',
'agent_PENTATW1',
'agent_MERIDBBS',
'agent_ANGL022',
'agent_CASHBBS',
'agent_HERITBBS',
'agent_ESTU BBS',
'agent_FALCOBBS',
'agent_AGXLBBS',
'agent_FILBBS',
'agent_WEXFBBS',
'agent_ABCO BBS',
'agent_ARCHWBBS',
'agent_GINAIBBS',
'agent_GLDWBBS',
'agent_ALLIABBS',
'agent_SOUTHBBS',
'agent_JPABBS',
'agent_REGIOBRS',
'agent_PERFBBS',
'agent_PRODBBS',
'agent_SIMBBS',
'agent_AIR CNWI',
'agent_GFSEXBBS',
'agent_FORWATW1',
'agent_SPECTEN4',
'agent_C T SEAA',
'agent_TRAKEBBS',
'agent_ALLWABBS',
'agent_ALLWAGLA',
'agent_A&OLBBS',
'agent_MEX CBBS',
'agent_FORM002',
'agent_REGIONWI',
'agent_JONESBBS',
'agent_EXECUBBS',
'agent_GIL IBBS',
'agent_JEM FBBS',
'agent_AIRWORL',
'agent_STRAIBBS',
'agent_DEUGRBBS',
'agent_ABBOTBBS',
'agent_CRNBBS',
'agent_BRUNEBRS',
'agent_MEDFRT',
'agent_ATLASBBS',
'agent_HENEWBBS',
'agent_LUXURY',
'agent_TECH BBS',
'agent_CLEOPBBS',
'agent_EXECBBS',
'agent_PARK BBS',
'agent_ATLANSS1',
'agent_DFSBBS',
'agent_BE FRBBS',
'agent_PHOENCAR',
'agent_EVOLUMAN',
'agent_SANDFBBS',
'agent_GR8FR8',
'agent_SOUNDBBS',
'agent_ALLIABHX',
'agent_ECLIPNWI',
'agent_K LINBBS',
'agent_CRM LBBS',
'agent_AERO BBS',
'agent_PETERBBS',
'agent_C K CBBS',
'agent_REPUBHX',
'agent_GLOB020',
'agent_GLCBBS',
'agent_SCANBBS',
'agent_BRISKBBS',
'agent_TFS LBBS',
'agent_ALPI BBS',
'agent_INTERGLA',
'agent_VIP FBBS',
'agent_OAST BRS',
'agent_MEABBS',
'agent_UNICBBS',
'agent_CORTEN',
'agent_EFM MBBS',
'agent_REEXBBS',
'agent_UNIEXPRE',
'agent_PETERBRS',
'agent_HAWK BBS',
'agent_CARDIMAN',
'agent_KAM FBBS',
'agent_FAR EBBS',
'agent_VIVA BBS',
'agent_LEVANBBS',
'agent_ROCK-BBS',
'agent_BENCOBBS',
'agent_INTERBBS',
'agent_FSYSTEMS',
'agent_CAROVBBS',
'agent_SENATBBS',
'agent_HORIZBBS',
'agent_EMBASBBS',
'agent_MORRIBBS',
'agent_TRANSRH1',
'agent_LIGBBS',
'agent_SIGNEBBS',
'agent_SOUTHBRS',
'agent_PENTABR5',
'agent_JAG-UBBS',
'agent_PIONEBBS',
'agent_SYSTEMAT',
'agent_BALTRBBS',
'agent_SUPERBBS',
'agent_CONNOBBS',
'agent_CHARLBBS',
'agent_AIR &BBS',
'agent_LV SHBBS',
'agent_NORMABBS',
'agent_AIR &TW1',
'agent_HEMISBBS',
'agent_RHENUBHX',
'agent_REGENBBS',
'agent_PRO-SBBS',
'agent_CHILTBBS',
'agent_KANGABBS',
'agent_CONCOBBS',
'agent_WESTEBBS',
'agent_MALTABBS',
'agent_LVSHNWI',
'agent_VANTAGEC',
'agent_FH BEABZ',
'agent_EUROPBBS',
'agent_ROJAYBBS',
'agent_WALKEBBS',
'agent_RCCOMBIN',
'agent_CH ROGLA',
'agent_TRANSS9',
'agent_EUROFBBS',
'agent_SUNBURYL',
'agent_JD FRBBS',
'agent_PRECIBBS',
'agent_BELLVBBS',
'agent_QUESTBBS',
'agent_PELICBBS',
'agent_YRC LBBS',
'agent_NORMAMAN',
'agent_IMMEDBBS',
'agent_SPECTBBS',
'agent_CAVALBBS',
'agent_PRESTBBS',
'agent_TFA LBBS',
'agent_WOODLBBS',
'agent_PERISBBS',
'agent_GFSLBBS',
'agent_DELIBBS',
'agent_IJS GBBS',
'agent_HEATHTW1',
'agent_DIAMOBBS',
'agent_FREIGNCL',
'agent_MENTFBBS',
'agent_PREMIBRS',
'agent_METROBHX',
'agent_AFI UMAN',
'agent_GLOBFRT',
'agent_PAULSBBS',
'agent_PENTANCL',
'agent_PDP FBBS',
'agent_UNEEKBBS',
'agent_PBS IBBS',
'agent_KINTEGLA',
'agent_BLACKBBS',
'agent_PMG WBBS',
'agent_ACTIOBBS',
'agent_SEKO MAN',
'agent_TOLLBRS',
'agent_STAPLMAN',
'agent_MAPCABBS',
'agent_TFS CBBS',
'agent_WILLIBBS',
'agent_KUEHNABZ',
'agent_JAMESBBS',
'agent_TG LOBBS',
'agent_SUTCHBBS',
'agent_CGCONBBS',
'agent_WARRALBA',
'agent_BLAIKBBS',
'agent_NNR GBBS',
'agent_BBS001',
'agent_DHL GGLA',
'agent_BURHBBS',
'agent_WORLDC',
'agent_FOCUSBBS',
'agent_OCEANSL3',
'agent_CARGOMAN',
'agent_GAC WBBS',
'agent_XPAND',
'agent_CAREBBS',
'agent_YRC LBHX',
'agent_MDFR EMA',
'agent_KINGSGLA',
'agent_LIFTFRT',
'agent_PANTEBBS',
'agent_PRIMELBA',
'agent_WORLDKT1',
'agent_CRANEBBS',
'agent_QUICKBBS',
'agent_PRIMEBBS',
'agent_AIR MBBS',
'agent_AIR MMAN',
'agent_AZTEKBBS',
'agent_TRANSBRS',
'agent_ROEHLBHX',
'agent_UNIQBBS',
'agent_L V SBBS',
'agent_UNSBBS',
'agent_FOURDBBS',
'agent_RHENBBS',
'agent_KINTEEMA',
'agent_PREMITW1',
'agent_ARAMEBBS',
'agent_HICGOIMP',
'agent_PENTANWI',
'agent_SANDRBBS',
'agent_CARLMAN',
'agent_ACTIVEFM',
'agent_F S MBBS',
'agent_GCL LBBS',
'agent_CARGONET',
'agent_PETRAGLA',
'agent_IFEGLOBA',
'agent_DGG BBS',
'agent_OPTIMUM',
'agent_SUPREME',
'agent_CLASSBBS',
'agent_TEAM SL3',
'agent_BRUNEBBS',
'agent_MARTIMAN',
'agent_PSFBBS',
'agent_CONCONP4',
'agent_CEVAECHT',
'agent_BROOKBBS',
'agent_KINGSBBS',
'agent_MAURIBBS',
'agent_DOMINO',
'agent_GBASERVI',
'agent_EURONILE',
'agent_BDPBBS',
'agent_EXPWW',
'agent_DYNAMBBS',
'agent_RADIUBBS',
'agent_KEY CMAN',
'agent_LHRGLOB',
'agent_RIF WMAN',
'agent_D M LBBS',
'agent_ATLANMAN',
'agent_DM LOBBS',
'agent_HELLMMAN',
'agent_COURIBBS',
'agent_BALTRMAN',
'agent_TGFMLBHX',
'agent_IMSBBS',
'agent_LOGWIBBS',
'agent_BLACKTHO',
'agent_IN TIBBS',
'agent_SDV BBBS',
'agent_AIRCABBS',
'agent_VELTAINT',
'agent_SANTBBS',
'agent_WOODLMAN',
'agent_WORLDSL3',
'agent_ACUMEBBS',
'agent_MOL LBBS',
'agent_TEAM BBS',
'agent_SAVINBBS',
'agent_INDWBBS',
'agent_TRANSTW1',
'agent_KERRYBBS',
'agent_NORMANWI',
'agent_LINEHBBS',
'agent_CAC AMAN',
'agent_KRASLOG',
'agent_SEKOGLA',
'agent_ROEHLBBS',
'agent_U FREBBS',
'agent_YLCBBS',
'agent_UNIEXMAN',
'agent_DREABBS',
'agent_ACE FSE7',
'agent_BRUNLOG',
'agent_KRPINTL',
'agent_KAMINBBS',
'agent_SOVERBBS',
'agent_INTEBBS',
'agent_KUEHNBHX',
'agent_TRANSMAN',
'agent_AIR SMAN',
'agent_IJS GMAN',
'agent_JGOODBBS',
'agent_BLACKMAN',
'agent_GENESBHX',
'agent_SIMARCO',
'agent_LEXINBBS',
'agent_DESPABBS',
'agent_METROLHR',
'agent_WORLDNWI',
'agent_ETA BBS',
'agent_X-PANBBS',
'agent_EMS CBBS',
'agent_CLOVEBBS',
'agent_TELENBBS',
'agent_OVERSBBS',
'agent_TRADEMAN',
'agent_CONNABBS',
'agent_KINTENCL',
'agent_YOURWBBS',
'agent_ZIEBBS',
'agent_ADVANTW1',
'agent_WFSINTL',
'agent_WILDERL',
'agent_KINGSMAN',
'agent_TNTUKBBS',
'agent_AIR STW1',
'agent_WORLDTW1',
'agent_PENTAABZ',
'agent_AVIATBBS',
'agent_TNT EBBS',
'agent_FEDBBS',
'agent_MAINFRT',
'agent_CONNEBBS',
'agent_SEKO BBS',
'agent_RHENULBA',
'agent_ASLBBS',
'agent_WORLDCAB',
'agent_CORVULBA',
'agent_WORLDCAR',
'agent_PANALGLA',
'agent_PUZZBBS',
'agent_VELTABBS']
